### ISSUE TITLE
Fails to install on Windows 10 with pip

### ISSUE THREAD

**Issue by reszelaz** [vasole/fisx#24]
I try to install fisx on Windows 10 with pip, well actually I try to install PyMca, but fisx is one of its dependencies. Both installations fails with:

```
    running install_lib
    copying build\lib.win32-2.7\fisx\DataDir.py -> C:\Python27\Lib\site-packages\fisx
    copying build\lib.win32-2.7\fisx\_fisx.pyd -> C:\Python27\Lib\site-packages\fisx
    byte-compiling C:\Python27\Lib\site-packages\fisx\DataDir.py to DataDir.pyc
    running install_data
    fisx to be installed in C:\Python27\Lib\site-packages\
    running install_egg_info
    running egg_info
    writing requirements to python\fisx.egg-info\requires.txt
    writing python\fisx.egg-info\PKG-INFO
    writing top-level names to python\fisx.egg-info\top_level.txt
    writing dependency_links to python\fisx.egg-info\dependency_links.txt
    reading manifest file 'python\fisx.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\ieuser\appdata\local\temp\pip-install-nenff2\fisx\setup.py", line 339, in <module>
        setup_requires=setup_requires,
      File "C:\Python27\lib\site-packages\setuptools\__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "C:\Python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Python27\lib\distutils\command\install.py", line 575, in run
        self.run_command(cmd_name)
      File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Python27\lib\site-packages\setuptools\command\install_egg_info.py", line 34, in run
        self.run_command('egg_info')
      File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 278, in run
        self.find_sources()
      File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 293, in find_sources
        mm.run()
      File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 524, in run
        self.add_defaults()
      File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 567, in add_defaults
        self.read_manifest()
      File "C:\Python27\lib\site-packages\setuptools\command\sdist.py", line 199, in read_manifest
        self.filelist.append(line)
      File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 466, in append
        path = convert_path(item)
      File "C:\Python27\lib\distutils\util.py", line 124, in convert_path
        raise ValueError, "path '%s' cannot be absolute" % pathname
    ValueError: path '/users/sole/GIT/fisx/LICENSE' cannot be absolute
```

Thanks in advance for any kind of help!

**Comment by vasole** [comment]
Please make sure to install a 64-bit version of Python. I stopped providing 32-bit wheels when my windows XP computer "died". For instance, pip install fisx=1.1.2 would work because that wheel was supplied in 2016.

**Comment by reszelaz** [comment]
Thanks for the hint. I confirm that 1.1.2 works correctly but it is not sufficient for PyMca. I will try to move to 64bit Python. Cheers!
